version: "3.4"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.8.1
    ports: 
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f localhost:9200"
        ]
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:8.8.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - xpack.security.enabled=false
    depends_on:
      - "elasticsearch"
    networks:
      - elastic
  
  filebeat:
    container_name: filebeat
    image: elastic/filebeat:8.8.1
    user: root
    command:
      - "-e"
      - "--strict.perms=false"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/usr/share/filebeat/logs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "elasticsearch"
    networks:
      - elastic
  
  logstash:
    depends_on:
      - "elasticsearch"
      - "kibana"
    image: logstash:8.8.1
    container_name: logstash
    ports:
      - 5044:5044
    expose: 
      - "5044"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOSTS}
    volumes:
     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
     - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elastic

networks:
  elastic: